name: CI workflow

on:
  push:
    branches:
      - main
      - features/*
  pull_request:

jobs:
  lint:
    name: Terraform Linting
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Run TFLint
        run: tflint --format=checkstyle > tflint-report.xml

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: tflint-report
          path: tflint-report.xml
          
      - name: Show Report Content
        run: cat tflint-report.xml

  tfsec:
    name: Terraform Security Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          format: checkstyle
          additional_args: --out=tfsec-report.xml
          soft_fail: false

      # - name: export tfsec
      #   run: tfsec --format=checkstyle > tfsec-report.xml

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report
          path: tfsec-report.xml

      - name: Show Report Content
        run: cat tfsec-report.xml